name: canker_detect
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.4'




dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  flutter_swiper_null_safety: ^1.0.2
  google_sign_in: ^6.0.2
  path_provider: ^2.0.14
  path: ^1.8.2
  camera: ^0.10.3+2
  http: ^0.13.6

  #flutter_launcher_icons: ^0.12.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  page_transition: ^2.0.9
  image_picker: ^0.8.7+2
  gallery_saver: ^2.3.2
  geocoding: ^2.1.0
  sleek_circular_slider: ^2.0.1
  get: ^4.6.5
  fluttertoast: ^8.2.2
  google_nav_bar: ^5.0.6
  easy_localization: ^3.0.2
  provider: ^6.0.5
  #image_picker: ^0.8.6
  collection: ^1.16.0
  image: ^3.3.0
  tflite_flutter_plus: ^0.0.1
  tflite_flutter_helper_plus: ^0.0.2
  flutter_staggered_grid_view: ^0.4.0-nullsafety.0
  uuid: ^4.0.0
  firebase_storage: ^11.2.6
  geolocator: ^10.0.1
  quickalert: ^1.0.2
  connectivity_plus: ^4.0.2

  hive: ^2.1.0
  hive_flutter: ^1.1.0
  time: ^2.1.0
  timezone: ^0.8.0
  weather: ^2.0.1
  weather_icons: ^3.0.0
  #new added


flutter_icons:
  image_path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/icons/
    - assets/weather/
    - assets/
    - assets/background/
    - assets/translations/
    - assets/translations/en-US.json
    - assets/translations/hi-IN.json
    - assets/translations/ur-PK.json
    - assets/icon/icon.png
    - assets/translations/
    - assets/labels.txt
    - assets/model_unquant.tflite
    - assets/labels_one.txt
    - assets/model_unquant_one.tflite

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

