name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart/setup-dart@v2
        with:
          dart-version: '2.19.2' # Use the minimum required Dart SDK version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
          channel: 'stable'

      - name: Display Flutter version
        run: flutter --version

      - name: Build APKs
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          mkdir -p release
          mv build/app/outputs/flutter-apk/* release/

      - name: Set Version Variables
        id: set_version
        run: echo "::set-env name=VERSION::v${{ github.run_number }}-alpha"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*  # Upload all files in the release directory
          tag_name: ${{ steps.set_version.outputs.VERSION }}
          title: ${{ steps.set_version.outputs.VERSION }}
          body: |
            Release notes for ${{ steps.set_version.outputs.VERSION }}
            - Add new feature
            - Fix bugs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: release/
