name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Version Variables
        id: set_version
        run: echo "::set-env name=VERSION::v${{ github.run_number }}-alpha"

      - name: Build APKs
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - run: flutter build appbundle --release

      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          tag_name: ${{ steps.set_version.outputs.VERSION }}
          title: ${{ steps.set_version.outputs.VERSION }}
          body: |
            Release notes for ${{ steps.set_version.outputs.VERSION }}
            - Add new feature
            - Fix bugs

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
