name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dart SDK
        run: |
          DART_VERSION="2.19.2"  # Replace with your desired Dart SDK version
          DART_SDK_URL="https://storage.googleapis.com/dart-archive/channels/stable/release/${DART_VERSION}/sdk/dartsdk-linux-x64-release.zip"
          mkdir -p /opt/dart
          curl -fsSL "$DART_SDK_URL" -o /tmp/dart-sdk.zip
          unzip -q /tmp/dart-sdk.zip -d /opt/dart
          export PATH="$PATH:/opt/dart/dart-sdk/bin"
          dart --version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
          channel: 'stable'

      - name: Display Flutter version
        run: flutter --version

      - name: Build APKs
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          mkdir -p release
          mv build/app/outputs/flutter-apk/* release/

      - name: Set Version Variables
        id: set_version
        run: echo "::set-env name=VERSION::v${{ github.run_number }}-alpha"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*  # Upload all files in the release directory
          tag_name: ${{ steps.set_version.outputs.VERSION }}
          title: ${{ steps.set_version.outputs.VERSION }}
          body: |
            Release notes for ${{ steps.set_version.outputs.VERSION }}
            - Add new feature
            - Fix bugs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: release/
