name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APKs
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Add Flutter Action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - run: flutter build appbundle --release

      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          tag_name: 'v1'
          title: 'demo'
          body: |
            Release notes for v1
            - Add new feature
            - Fix bugs

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
